USE mini_project_be;
CREATE TABLE IF NOT EXISTS Users (
  userId INT NOT NULL AUTO_INCREMENT,
  email VARCHAR(319) UNIQUE NOT NULL,
  nickname VARCHAR(20) UNIQUE NOT NULL,
  password CHAR(60) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY(userId)
);
CREATE TABLE IF NOT EXISTS Posts (
  postId INT NOT NULL AUTO_INCREMENT,
  title VARCHAR(50) NOT NULL,
  content VARCHAR(1000) NOT NULL,
  imageKey VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  userId INT NOT NULL,
  categoryId TINYINT NOT NULL,
  PRIMARY KEY (postId),
  FOREIGN KEY (userId) REFERENCES Users(userId)
);
CREATE TABLE IF NOT EXISTS Comments (
  commentId INT NOT NULL AUTO_INCREMENT,
  content VARCHAR(100) NOT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  userId INT NOT NULL,
  postId INT NOT NULL,
  PRIMARY KEY(commentId),
  FOREIGN KEY(userId) REFERENCES Users(userId),
  FOREIGN KEY(postId) REFERENCES Posts(postId)
);
CREATE TABLE IF NOT EXISTS Likes (
  userId INT NOT NULL,
  postId INT NOT NULL,
  PRIMARY KEY(userId, postId),
  FOREIGN KEY(userId) REFERENCES Users(userId),
  FOREIGN KEY(postId) REFERENCES Posts(postId)
);